items:
- name: Kubernetes
  include: { mode: link, path: orchestrated/toc_p.yaml }
- name: VM / Baremetal
  href: manual/deploy-ydb-on-premises.md
- name: Deploying a single-node cluster
  include: { mode: link, path: ../getting_started/self_hosted/toc_p.yaml }
- name: Configuration
  href: configuration/config.md
- name: BlobStorage production configurations
  href: ../administration/production-storage-config.md

