items:
- name: Развертывание YDB
  href: deploy-ydb-on-premises.md
- name: Развертывание YDB с функцией Federated Query
  href: deploy-ydb-federated-query.md
- name: Развертывание коннектора
  href: connector.md
