generic:
  mlock: false

  logging:
    stderr: false

  server:
    http_port: 8788
    https_port: 8789
    ca_cert_file: path/to/ca.crt
    ssl_cert_file: path/to/ssl.crt

  auth:
    token_file: path/to/token_file
    federated_creds:
      token_service_endpoint: "grpcs://tokens.net:443"
      k8s_token_path: "path/to/federated_token"
      service_account_id: "project0tydb_sa"

oidc:
  client_id: "client-id"
  secret_name: "secret-name"
  session_service_endpoint: "grpcs://ss.private-api.cloud-preprod.net:8655"
  session_service_token_name: "token-name"
  authorization_server_address: "https://auth-preprod.cloud.ru"
  access_service_type: "yandex_v2"
  allowed_proxy_hosts:
    - "*.host.net"
    - "*.host-team.ru"
