generic:
  mlock: false

  logging:
    stderr: false

  server:
    http_port: 8788
    https_port: 8789
    ca_cert_file: path/to/ca.crt
    ssl_cert_file: path/to/ssl.crt

  auth:
    # only one token_file or federated_creds should be provided
    token_file: path/to/tokenator_config
    federated_creds:
      token_service_endpoint: "grpcs://tokens.net:443"
      k8s_token_path: "path/to/federated_token"
      service_account_id: "project0tydb_sa"

oidc:
  client_id: "client-id"
  secret_name: "oidc-secret"
  session_service_endpoint: "grpcs://ss.private-api.cloud-preprod.yandex.net:8655"
  session_service_token_name: "ss-token"
  authorization_server_address: "https://auth-preprod.cloud.yandex.ru"
  access_service_type: "yandex_v2"
  allowed_proxy_hosts:
    - "*.yandex.net"
    - "*.yandex-team.ru"
