generic:
  mlock: false

  logging:
    stderr: false

  server:
    http_port: 8788
    https_port: 8789
    ca_cert_file: path/to/ca.crt
    ssl_cert_file: path/to/ssl.crt

  auth:
    token_file: path/to/tokenator_config

oidc:
  client_id: "client-id"
  secret_name: "oidc-secret"
  session_service_endpoint: "grpcs://ss.private-api.cloud-preprod.yandex.net:8655"
  session_service_token_name: "ss-token"
  authorization_server_address: "https://auth-preprod.cloud.yandex.ru"
<<<<<<< HEAD
  access_service_type: "yandex_v2"
=======
  access_service_type: "yandex"
>>>>>>> b14ae95980 (renamed EAuth profile to EAccessServiceTypeEAccessServiceType)
  allowed_proxy_hosts:
    - "*.yandex.net"
    - "*.yandex-team.ru"
