items:
- name: Первоначальное развёртывание
  href: initial-deployment/index.md
  include:
    mode: link
    path: initial-deployment/toc_p.yaml
- name: Подготовка виртуальных машин с Terraform
  href: preparing-vms-with-terraform.md
- name: Перезапуск
  href: restart.md
- name: Обновление конфигурации
  href: update-config.md
- name: Обновление исполняемого файла
  href: update-executable.md
- name: Наблюдаемость
  include:
    mode: link
    path: observability/toc_p.yaml
