items:
- name: Подготовка к развёртыванию
  href: deployment-preparation.md
- name: Развёртывание кластера с использованием конфигурации V1 (OLTP)
  href: deployment-configuration-v1.md
- name: Развёртывание кластера с использованием конфигурации V2 (OLTP)
  href: deployment-configuration-v2.md
- name: Развёртывание кластера под аналитическую нагрузку (OLAP)
  href: deployment-configuration-olap.md
