items:
- name: Развертывание
  include:
    mode: link
    path: ../../deploy/toc_p.yaml
- name: Управление дисковой подсистемой кластера
  include:
    mode: link
    path: ../../maintenance/manual/toc_p.yaml
- name: Мониторинг
  href: monitoring.md
- name: Логирование
  href: logging.md
- name: Резервное копирование и восстановление
  href: backup-and-recovery.md
- name: Обновление
  href: upgrade.md
- name: Изменение конфигурации актор-системы
  href: ../../maintenance/manual/change_actorsystem_configs.md
- name: Управление конфигурацией кластера
  items:
  - name: Обзор конфигурации
    href: ../../maintenance/manual/config-overview.md
  - name: Статическая конфигурация кластера
    href: ../../deploy/configuration/config.md
  - name: Динамическая конфигурация кластера
    href: ../../maintenance/manual/dynamic-config.md
  - name: DSL конфигурации кластера
    href: ../../maintenance/manual/dynamic-config-selectors.md
  - name: Временная конфигурация
    href: ../../maintenance/manual/dynamic-config-volatile-config.md
  - name: Изменение конфигураций через CMS
    href: ../../maintenance/manual/cms.md
- name: Системные таблицы
  href: system-views.md
- name: Обслуживание без потери доступности
  href: maintenance-without-downtime.md
