items:
- name: Overview
  href: index.md
- name: System requirements
  href: system-requirements.md
- name: Ansible
  include:
    mode: link
    path: ansible/toc_p.yaml
- name: Kubernetes
  include:
    mode: link
    path: kubernetes/toc_p.yaml
- name: Manual
  include:
    mode: link
    path: manual/toc_p.yaml
