items:
- name: Подготовка к добавлению нового диска
  href: disk-addition-preparation.md
- name: Добавление нового диска в кластер (конфигурация V1)
  href: add-new-disk-v1.md
- name: Добавление нового диска в кластер (конфигурация V2)
  href: add-new-disk-v2.md