name: Ya-Build-and-Test-Provisioned

on:
  workflow_dispatch:
    inputs:
      build_target:
        type: string
        default: "ydb/"
        description: "limit build and test to specific target"
      sanitizer:
        type: choice
        default: "none"
        description: "sanitizer type"
        options:
          - none
          - address
          - memory
          - thread
          - undefined
          - leak
      runner_label:
        type: string
        default: "ya-make"
        description: "runner label"
      run_build:
        type: boolean
        default: true
        description: "run build"
      run_tests:
        type: boolean
        default: true
        description: "run tests"
      testmo_source:
        type: string
        default: "ya-x86-64"
        description: "testmo source"
  workflow_call:
    inputs:
      build_target:
        type: string
        default: "ydb/"
      sanitizer:
        type: string
        default: "none"
      run_build:
        type: boolean
        default: true
      run_tests:
        type: boolean
        default: true
      runner_label:
        type: string
        default: "ya-make"
      testmo_source:
        type: string
        default: "ya-x86-64"

jobs:
  main:
    uses: ./.github/workflows/build_and_test_ya.yml
    with:
      runner_kind: provisioned
      runner_label: ${{ inputs.runner_label }}
      build_target: ${{ inputs.build_target }}
      sanitizer: ${{ inputs.sanitizer }}
      run_build: ${{ inputs.run_build }}
      run_tests: ${{ inputs.run_tests }}
      log_suffix: ${{ inputs.testmo_source }}
    secrets: inherit
