name: Nightly-run
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      test_label_regexp:
        required: false
        type: string

jobs:
  cmake_x86_64:
    name: Build/test x86_64
    strategy:
      matrix: ${{ fromJSON(vars.NIGHTLY_CMAKE_X64_MATRIX) }}
      fail-fast: false

    uses: ./.github/workflows/build_and_test_provisioned.yml
    with:
      runner_label: auto-provisioned
      sanitizer: ${{matrix.sanitizer}}
      test_label_regexp: ${{inputs.test_label_regexp}}
    secrets: inherit

  cmake_arm64:
    name: Build/test ARM64
    strategy:
      matrix: ${{ fromJSON(vars.NIGHTLY_CMAKE_ARM64_MATRIX) }}
      fail-fast: false
    uses: ./.github/workflows/build_and_test_provisioned.yml
    with:
      runner_label: ARM64
      sanitizer: ${{matrix.sanitizer}}
      extra_compile_flags: "-DMKQL_DISABLE_CODEGEN"
      test_label_regexp: ${{inputs.test_label_regexp}}
    secrets: inherit

  ya_x86_64:
    name: Build/test x86_64 using YA
    uses: ./.github/workflows/build_and_test_ya_provisioned.yml
    secrets: inherit
    strategy:
      matrix: ${{ fromJSON(vars.NIGHTLY_YA_X64_MATRIX) }}
      fail-fast: false
    with:
      runner_label: auto-provisioned
      build_preset: ${{ matrix.build_preset }}
      build_target: ydb/
      run_build: true
      run_tests: true