name: Nightly-run
on: 
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      test_label_regexp:
        required: false
        type: string
  
jobs:
  build_ondemand:
    name: Build/test X64
    strategy:
      matrix: ${{ fromJSON(vars.NIGHTLY_ONDEMAND_MATRIX) }}
      fail-fast: false

    uses: ./.github/workflows/build_and_test_ondemand.yml
    with:
      sanitizer: ${{matrix.sanitizer}}
      test_label_regexp: ${{inputs.test_label_regexp}}
    secrets: inherit

  build_provisioned:
    name: Build/test ARM64
    strategy:
      matrix: ${{ fromJSON(vars.NIGHTLY_PROVISIONED_MATRIX) }}
      fail-fast: false
    uses: ./.github/workflows/build_and_test_provisioned.yml
    with:
      runner_label: ARM64
      sanitizer: ${{matrix.sanitizer}}
      extra_compile_flags: "-DMKQL_DISABLE_CODEGEN"
      test_label_regexp: ${{inputs.test_label_regexp}}
    secrets: inherit
