name: Update dstool package

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        type: string
        default: ""

jobs:
  update-dstool:
    name: Update dstool package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.13'

      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade pip
          pip install build twine

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Compile proto files and build package
        run: |
          set -ex
          ls
          cd ${{ github.workspace }}/ydb
          ls
          ./ydb/apps/dstool/compile_protos.py --ydb-root ./
          mv ydb/apps/dstool/setup.py .
          python -m build

#      - name: Upload package to PyPI
#        env:
#          TWINE_USERNAME: __token__
#          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#        run: |
#          set -ex
#          cd ${{ github.workspace }}/ydb
#          python -m twine upload dist/*
